// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempleTours.Models;

namespace TempleTours.Migrations
{
    [DbContext(typeof(TempleToursContext))]
    [Migration("20220321195053_TimeSlots")]
    partial class TimeSlots
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("TempleTours.Models.Appointment", b =>
                {
                    b.Property<long>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppointmentTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("TempleTours.Models.TimeSlot", b =>
                {
                    b.Property<long>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeSlotDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeSlotStart")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeSlotId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            TimeSlotId = 1L,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 2L,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 3L,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 4L,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 5L,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 6L,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 7L,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 8L,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 9L,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 10L,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 11L,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 12L,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 13L,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 14L,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 15L,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 16L,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 17L,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 18L,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 19L,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 20L,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 21L,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 22L,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 23L,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 24L,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 25L,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 26L,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 27L,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 28L,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 29L,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 30L,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 31L,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 32L,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 33L,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 34L,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 35L,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 36L,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 37L,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 38L,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 39L,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 40L,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 41L,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 42L,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 43L,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 44L,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 45L,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 46L,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 47L,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 48L,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 49L,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 50L,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 51L,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 52L,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 53L,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 54L,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 55L,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 56L,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 57L,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 58L,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 59L,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 60L,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 61L,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 62L,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 63L,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 64L,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 65L,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 66L,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 67L,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 68L,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 69L,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 70L,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 71L,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 72L,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 73L,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 74L,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 75L,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 76L,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 77L,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 78L,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 79L,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 80L,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 81L,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 82L,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 83L,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 84L,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 85L,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 86L,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 87L,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 88L,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 89L,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 90L,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 91L,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "8:00 PM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
