// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempleTours.Models;

namespace TempleTours.Migrations
{
    [DbContext(typeof(TempleToursContext))]
    partial class TempleToursContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("TempleTours.Models.Appointment", b =>
                {
                    b.Property<long>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppointmentId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("TempleTours.Models.TimeSlot", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeSlotDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeSlotStart")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeSlotId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            TimeSlotId = 1,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 2,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 3,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 4,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 5,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 6,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 7,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 8,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 9,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 10,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 11,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 12,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 13,
                            TimeSlotDay = "Monday",
                            TimeSlotStart = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 14,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 15,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 16,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 17,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 18,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 19,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 20,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 21,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 22,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 23,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 24,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 25,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 26,
                            TimeSlotDay = "Tuesday",
                            TimeSlotStart = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 27,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 28,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 29,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 30,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 31,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 32,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 33,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 34,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 35,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 36,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 37,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 38,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 39,
                            TimeSlotDay = "Wednesday",
                            TimeSlotStart = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 40,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 41,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 42,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 43,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 44,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 45,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 46,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 47,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 48,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 49,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 50,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 51,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 52,
                            TimeSlotDay = "Thursday",
                            TimeSlotStart = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 53,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 54,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 55,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 56,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 57,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 58,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 59,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 60,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 61,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 62,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 63,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 64,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 65,
                            TimeSlotDay = "Friday",
                            TimeSlotStart = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 66,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 67,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 68,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 69,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 70,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 71,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 72,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 73,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 74,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 75,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 76,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 77,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 78,
                            TimeSlotDay = "Saturday",
                            TimeSlotStart = "8:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 79,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "8:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 80,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "9:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 81,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "10:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 82,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "11:00 AM"
                        },
                        new
                        {
                            TimeSlotId = 83,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "12:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 84,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "1:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 85,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "2:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 86,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "3:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 87,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "4:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 88,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "5:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 89,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "6:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 90,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "7:00 PM"
                        },
                        new
                        {
                            TimeSlotId = 91,
                            TimeSlotDay = "Sunday",
                            TimeSlotStart = "8:00 PM"
                        });
                });

            modelBuilder.Entity("TempleTours.Models.Appointment", b =>
                {
                    b.HasOne("TempleTours.Models.TimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
